### ISSUE TITLE
Add Method for Ingesting Files as Context

### ISSUE THREAD

**Issue by mason-at-pieces** [mason-at-pieces/pieces-copilot-sdk#2]
# Overview

The idea of this is to allow users to "upload" any info into a conversation and then that information is used as context in the conversation.

This ingestion method should be separate from the current methods for reusability in other methods.

## Tasks

- [ ] Create an ingestion method that lets people upload files (can start with just code files and you can use the language list I have in `/lib/const.ts` to check the file extensions)
  - [ ] Parameters should take a `conversationId` and either a file or directory path
- [ ] Should return one or an array of seeded assets which can then be used as relevance when creating a conversation or prompting a conversation.
- [ ] Need to add an optional parameter in the `createConversation` method that is of the type `SeededAsset | SeededAsset[]`.
- [ ] If the parameter exists, ensure it gets added when creating a new conversation.
  - [ ] Also need to ensure that we are accounting for any context that is added mid-conversation, which should be appended to the conversation context.

**Comment by seantiz** [comment]
But how do we fetch the body of an `Asset` to return it or pass it in as an argument? This is where i hit a wall with the original OpenAPI schema

**Comment by mason-at-pieces** [comment]
@seantiz If I understand your question correctly, it could be as simple as getting a list of assets, getting the id for whatever asset you want to use for context, and then using that id you can get the body of the asset.

**Comment by shivay-at-pieces** [comment]
@mason-at-pieces is this different than adding the context via files to qGPTRelevanceInput seed?
